### ISSUE TITLE
[feature request]support azure openai api

### ISSUE THREAD

**Issue by HaveF** [chatgptui/desktop#3]
Hi, Thanks for this repo 👋 

It looks great. I didn't try it yet(just waiting for stable version 😄)
I wonder could it possible to add support azure openai api?
https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/

Because openAI is not accessible to everyone on the planet...

**Comment by chatgptui** [comment]
I never thought about using it. I will check the API.

**Comment by chatgptui** [comment]
I've implemented this in https://github.com/chatgptui/desktop/commit/75287682410a56a54de5e09668848f18fd54f40b (included in v0.17.0, which will be released in about 30 min), but I have no idea if the implementation is correct. I don't have access to Azure OpenAI service because it requires a company email address.

**Comment by HaveF** [comment]
> Azure OpenAI Service is currently available to customers via an application form. 

Oops! I haven't notice that. Sorry, I also can't access the endpoint.

> As part of Microsoft's commitment to responsible AI, we are designing and releasing Azure OpenAI Service with the intention of protecting the rights of individuals and society and fostering transparent human-computer interaction. For this reason, we currently limit the access and use of Azure OpenAI, including limiting access to the ability to modify content filters and modify abuse monitoring.

As soon as it is open to public, I'll test it.

Sorry
